name: 'Replicated KOTS release'
description: 'Create a Replicated KOTS release on a channel'
inputs:
  replicated-app:
    description: 'Replicated App Slug'
    required: true
    default: 'my-app-enterprise'
  replicated-api-token:
    description: 'Replicated API Token'
    required: true
    default: ''
  replicated-api-origin:
    description: 'Replicated API Origin'
    default: 'https://api.replicated.com/vendor'
  yaml-dir:
    description: 'Directory containing KOTS application manifests'
    required: true
    default: 'manifests'
  release-notes:
    description: 'Release notes for the promoted release'
    required: true
    default: 'GitHub Action release of ${GITHUB_REF} triggered by ${GITHUB_ACTOR}: [${GITHUB_SHA::7}](https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})'
  promote-channel:
    description: 'Channel to promote the release into'
    required: true
    default: '${GITHUB_REF}'
  version:
    description: 'Release version'
    required: true
    default: '${GITHUB_SHA::7}'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '/replicated release create --promote="${{ inputs.promote-channel }}" --ensure-channel --yaml-dir="${{ inputs.yaml-dir }}" --release-notes="${{ inputs.release-notes }}" --version="${{ inputs.version }}"'
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}
    REPLICATED_API_ORIGIN: ${{ inputs.replicated-api-origin }}
